### ISSUE TITLE
Missing Galaxy wheels

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/starforge#196]
- [ ] bagit: https://github.com/LibraryOfCongress/bagit-python/pull/109, fixed since release 1.7.0, need to wait for bdbag to update its pin on bagit
- [x] bdbag: https://github.com/galaxyproject/galaxy/pull/6324
- [ ] beaker: wheel missing for Python 2.7 too
- [ ] bunch: wheel missing for Python 2.7 too, unmaintained, could be replaced with munch
- [x] **bx-python**: https://github.com/galaxyproject/starforge-recipes/pull/13
- [ ] cheetah3: https://github.com/CheetahTemplate3/cheetah3/issues/4
- [ ] cliff: https://bugs.launchpad.net/python-cliff/+bug/1760157 https://review.openstack.org/#/c/574846/ https://github.com/galaxyproject/galaxy/pull/6469
- [x] cloudbridge: https://github.com/gvlproject/cloudbridge/pull/118 https://github.com/galaxyproject/starforge-recipes/pull/18
- [ ] deprecation: https://github.com/briancurtin/deprecation/pull/33
- [ ] dictobj: wheel missing for Python 2.7 too
- [ ] dogpile.cache: wheel missing for Python 2.7 too, has support for universal wheels, https://bitbucket.org/zzzeek/dogpile.cache/issues/126/provide-wheels-on-pypi
- [ ] fabric3: https://github.com/mathiasertl/fabric/pull/49
- [ ] functools32: https://github.com/michilu/python-functools32/issues/4
- [ ] future: wheel missing for Python 2.7 too, https://github.com/PythonCharmers/python-future/issues/250
- [ ] mako wheel missing for Python 2.7 too, https://bitbucket.org/zzzeek/mako/pull-requests/26/build-universal-wheels-drop-python-30-32/diff
- [x] **markupsafe**: https://github.com/pallets/markupsafe/issues/45 https://github.com/galaxyproject/starforge-recipes/pull/24
- [ ] msgpack: wheels available for Python 2.7, 3.5 and 3.6 (support for 3.4 dropped in release 0.5.0)
- [ ] munch: https://github.com/Infinidat/munch/pull/33 , should be fixed in next release (> 2.3.2)
- [x] netifaces: https://github.com/galaxyproject/galaxy/pull/6324
- [ ] nodeenv
- [ ] os-service-types: missing Python 2.7 wheel
- [ ] osc-lib: missing Python 2.7 wheel
- [ ] prettytable: wheel missing for Python 2.7 too, unmaintained
- [x] **psutil**: https://github.com/giampaolo/psutil/issues/900 https://github.com/galaxyproject/starforge-recipes/pull/17
- [ ] pycparser: universal wheel missing, https://github.com/eliben/pycparser/issues/288
- [x] pycrypto: https://github.com/galaxyproject/galaxy/pull/6324
- [ ] pyinotify: https://github.com/seb-m/pyinotify/issues/111
- [ ] pyjwkest
- [ ] pyperclip: wheel missing for Python 2.7 too, https://github.com/asweigart/pyperclip/pull/131
- [ ] pysam: missing osx wheel, https://github.com/pysam-developers/pysam/issues/722 https://github.com/galaxyproject/starforge-recipes/pull/32
- [ ] pysftp
- [x] **python-lzo**: https://github.com/galaxyproject/starforge-recipes/pull/3
- [ ] python-openid: unmaintained, replace with [python-openid2](https://github.com/ziima/python-openid) ?
- [x] **pyyaml**: https://github.com/yaml/pyyaml/issues/43 https://github.com/galaxyproject/starforge-recipes/pull/19
- [ ] repoze.lru: https://github.com/repoze/repoze.lru/pull/29
- [ ] simplejson: wheel missing for Python 2.7 too, https://github.com/simplejson/simplejson/issues/181
- [ ] sqlalchemy-migrate: https://review.openstack.org/#/c/577002/
- [ ] sqlalchemy-utils: wheel missing for Python 2.7 too
- [ ] sqlalchemy: wheel missing for Python 2.7 too
- [ ] tempita: wheel missing for Python 2.7 too
- [ ] tzlocal: wheel missing for Python 2.7 too
- [ ] unicodecsv: missing Python 2.7 wheel
- [ ] **uwsgi**: https://github.com/unbit/uwsgi/issues/816
- [ ] warlock: wheel missing for Python 2.7 too
- [x] **watchdog**: https://github.com/gorakhargosh/watchdog/issues/428 https://github.com/galaxyproject/starforge-recipes/pull/21
- [x] **wrapt**: wheel missing for Python 2.7 too, https://github.com/GrahamDumpleton/wrapt/issues/39 https://github.com/GrahamDumpleton/wrapt/pull/105 https://github.com/galaxyproject/starforge-recipes/pull/25

**Comment by nsoranzo** [comment]
@natefoo Can you help with this? Having `python-lzo`, `pyyaml` and `bx-python` Python3 wheels would help a lot!

**Comment by natefoo** [comment]
For uWSGI, we should switch to [pyuwsgi](https://pypi.org/project/pyuwsgi/) ([dev](https://github.com/lincolnloop/pyuwsgi-wheels)).

**Comment by nsoranzo** [comment]
Migrated to https://github.com/galaxyproject/starforge-recipes/issues/26 .
